### PR TITLE
fix: Make it possible to load natives premain

### LINKED ISSUE #621: [Bug]: Unable to load into Nightreign after latest patch with me3 + Seamless Coop
### What happened?

Image

"A fatal error has occurred and the process has been aborted:

Method "SignIn" is not available
nrsc\cs\auto_control_api\auto_control_api.cpp
20"

I am getting this error message with the latest version of Seamless Coop and me3 when I choose to continue my save at the main menu.  It loads for a second, and then the error occurs and the process closes.  Disabled antivirus just to make sure it wasn't that.  Everything was flawless before the latest seamless coop update.  Launching Seamless Coop without me3 it also loads into the game fine, seems to only happen when using it with me3.  I disabled all other mods except seamless coop and the issue remained.

### Version

v0.9.0

### What operating system are you seeing this problem on?

Windows

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by garyttierney**
Fixes #621

### CODE REVIEW

File: crates/mod-protocol/src/native.rs [hunk 1]
```diff
@@ -48,6 +57,8 @@ pub struct Native {
 
     /// An optional symbol to be called when this native successfully is queued for unload.
     pub finalizer: Option<String>,
+
+    pub load_during: Option<NativeLoadOrder>,
```
Comment (Dasaav-dsv) [inline crates/mod-protocol/src/native.rs]: A consideration: should this be something as simple as `load_early: bool`? It is not descriptive of the actual implementation (could be handy for future games with a different lifecycle) and means about as much to a user looking to fix a mod like Seamless Co-op (while also being simpler). We discussed the possible points for a native to be loaded and it's effectively just these two, so I don't see expanding the `NativeLoadOrder` enum.

**Review by Dasaav-dsv — CHANGES_REQUESTED** [review]

**Review by Dasaav-dsv — APPROVED** [review]

**Review by Dasaav-dsv — APPROVED** [review]
