### PR TITLE
fix: Don't list non-profile files

### LINKED ISSUE #306: [Bug]: `profile list` lists directories and extensions
### What happened?

Let's say I have a profile `~/.config/me3/profiles/profile1.me3`

And for convenience of using relative paths, the mods are in `~/.config/me3/profiles/profile1-mods`

`me3 profile list` will list both.

Also, the list includes extensions but `me3 profile show` expects a name without extension.

Files with other extensions should probably be ignored? Include `.toml` or only `.me3`?

### Version

v0.6.1 (Latest) - actually using [latest CI build from main branch](https://github.com/garyttierney/me3/actions/workflows/publish.yml?query=branch%3Amain) (278fd2e)

### What operating system are you seeing this problem on?

Linux

### Relevant log output

```shellsession
$ me3 profile list
profile1.me3
profile1-mods
$ me3 profile show profile1-mods #nothing
$ me3 profile show profile1.me3 #nothing
$ me3 profile show profile1 #ok
● Mod Profile
[...]
```

### PR DESCRIPTION
**Pull request by garyttierney**
Fixes #306

### CODE REVIEW

File: crates/cli/src/commands/profile.rs [hunk 1]
```diff
@@ -72,7 +72,16 @@ pub fn list(config: Config) -> color_eyre::Result<()> {
 
     for profile_entry in std::fs::read_dir(profile_dir)? {
         match profile_entry {
-            Ok(profile) => println!("{}", profile.file_name().to_string_lossy()),
+            Ok(profile) if profile.path().extension().is_some_and(|ext| ext == "me3") => {
+                let profile_name = profile
+                    .path()
+                    .file_stem()
+                    .map(|stem| stem.to_owned())
+                    .expect("must have a filename");
```
Comment (Dasaav-dsv) [inline crates/cli/src/commands/profile.rs:80]: Should this be a panic or a warning, e.g. when there is a file called just ".me3" in the directory?

Comment (garyttierney) [reply crates/cli/src/commands/profile.rs:80]: I don't think this is possible because we check `extension()`, let me double check

Comment (Dasaav-dsv) [reply crates/cli/src/commands/profile.rs:80]: Oh, you are absolutely right, had no idea.

**Review by Dasaav-dsv — APPROVED** [review]
